#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
. ~/.profile

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

if [[ "$TERM" == linux ]]; then
    $HOME/bin/fbterm-bg $HOME/Pictures/1366293872__.jpg
    export TERM='fbterm'
fi
#
# Editors
#

export EDITOR='vim'
export VISUAL='open -a Emacs'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $(yarn global bin)
  $HOME/.composer/vendor/bin
  /usr/local/{bin,sbin}
  /usr/bin
  /usr/local/mysql/bin
  $HOME/bin
  $HOME/.dnx/runtimes/dnx-mono.1.0.0-rc2-20221/bin
  $HOME/gcc-arm-none-eabi/bin
  /usr/local/opt/llvm/bin
  $HOME/.rvm/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

function au(){
    AURA="$(aura "$@")"

    if echo "$AURA" | grep -q '^aura >>= .*You have to use `.*sudo.*` for that.*$'
    then
        sudo aura "$@"
    else
        echo "$AURA"
    fi
}

function audl(){
    for i in "$@"
    do
        curl -s https://aur.archlinux.org/packages/$(echo $i | cut -c1,2)/$i/$i.tar.gz | tar zxvf -
    done
}

function cm()
{
    set -o pipefail
    $@ 2>&1  | colout -t cmake | colout -t g++
}

# Need to make this use scat

function json() 
{
    local COMMAND=""
    local TMP=$(mktemp)
    if [ -t 0 ]; then
        if [ $# -gt 0 ]; then
            COMMAND="$@"
        fi
    else
        COMMAND=$(/bin/cat)
    fi

    echo ${COMMAND} | python -mjson.tool | colout -t json
}

function code() 
{
    VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*
}
