#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Fuck XOFF
stty ixany
stty ixoff -ixon
stty stop undef
stty start undef

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.zprofile
source $HOME/.aliases
export PATH=$PATH:/home/ed/.gem/ruby/2.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl:$HOME/bin:$HOME/go/bin:$HOME/.cabal/bin:$HOME/.cask/bin
export PANEL_FIFO="/tmp/panel-fifo"
export DWMFIFO="/tmp/dwm.fifo"
export GOPATH="$HOME/go"

setopt no_hist_verify
setopt HIST_IGNORE_DUPS
[ -r /etc/profile.d/cnf.sh ] && . /etc/profile.d/cnf.sh

eval "$(fasd --init zsh-hook zsh-ccomp zsh-wcomp posix-alias posix-hook)"
eval `dircolors ~/.dircolors`

setopt no_hist_verify
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
     rm -rf "${SSH_ENV}"
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
     echo succeeded
     chmod 600 "${SSH_ENV}"
     . "${SSH_ENV}" > /dev/null
     /usr/bin/ssh-add ~/.ssh/git
     /usr/bin/ssh-add ~/.ssh/id-rsa;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     #ps ${SSH_AGENT_PID} doesn't work under cywgin
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
         start_agent;
     }
else     
     start_agent;
fi
